### PR TITLE
Embed files

### PR DESCRIPTION
**Pull request by LorenzGardner**
Add support for embedded files.

provided an array or resource files to embed nexe will now base64 encode the files into strings in a new module nexeres. From inside your application doing a require('nexeres').keys() will give you back an array of all the embedded files. and require('nexeres').get(fileName) will give you back the given file. 

They fileName is a string match, and to the relative path from the resource root dir. The hello world example has been changed to embed the message.txt file as an example.

I tested this with a web server that added 125 static files as embedded files. Performance was good, but then again total memory foot print was less than 3mb. I would expect things to go bad if you tried to embed say a large video file.

If you still want to run your app as normal node app you will need to wrap a require('nexeres') in a try catch statement and when not present use fs.readFileSync to get the data.

### CODE REVIEW

**Comment by LorenzGardner** [comment]
Addresses issues: #77

**Comment by RainbowDashDC** [comment]
Love the idea of using res in this, I'll check this out later and make sure it doesn't create any issues. However from how it looks, a breif skim, it should be fine. Thanks for the work!

**Comment by RainbowDashDC** [comment]
I get
```javascript
module.js:340
    throw err;
          ^
Error: Cannot find module 'nexeres'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at nexe.js:31:90
    at Array.call.C:\Users\Jared\Desktop\nexe\examples\hello-world\index.js.http [as 0] (nexe.js:50:11)
    at initModule (nexe.js:29:11)
    at Array.forEach (native)
    at nexe.js:39:8
    at nexe.js:46:4
``` when building and then running the hello-world example, and it's not very clear on how to *exactly* use it.

**Comment by RainbowDashDC** [comment]
Works great!

**Pull request merged**
